import sounddevice as sd
import librosa as l
import time
import numpy as np

y_drums, sr = l.load("C:\\Users\\jappa\\Repos\\sr_proto\\mir_1\\stems_demucs\\htdemucs\\twofriends\\drums.mp3", sr=48000)
y_vocals, sr = l.load("C:\\Users\\jappa\\Repos\\sr_proto\\mir_1\\stems_demucs\\htdemucs\\twofriends\\vocals.mp3", sr=48000)
y_melody, sr = l.load("C:\\Users\\jappa\\Repos\\sr_proto\\mir_1\\stems_demucs\\htdemucs\\twofriends\\other.mp3", sr=48000)
y_bass, sr = l.load("C:\\Users\\jappa\\Repos\\sr_proto\\mir_1\\stems_demucs\\htdemucs\\twofriends\\bass.mp3", sr=48000)


# D = l.stft(y, n_fft=2048, hop_length=512)
# D_fast = l.phase_vocoder(D, rate=0.9, hop_length=512)
# y_fast = l.istft(D_fast)


'''Generated by Gemini'''
new_rate = 1.2
# Conceptual modification
y_harmonic_vocals, y_percussive_vocals = l.effects.hpss(y_vocals)
y_harmonic_melody, y_percussive_melody = l.effects.hpss(y_melody)
y_harmonic_bass, y_percussive_bass = l.effects.hpss(y_bass)


# 1. Process harmonic part with the Phase Vocoder (it handles smooth sounds well)
D_harm_vocals = l.stft(y_harmonic_vocals, n_fft=2048, hop_length=512)
D_harm_melody = l.stft(y_harmonic_melody, n_fft=2048, hop_length=512)
D_harm_bass = l.stft(y_harmonic_bass, n_fft=2048, hop_length=512)
D_fast_harm_v = l.phase_vocoder(D_harm_vocals, rate=new_rate, hop_length=512)
D_fast_harm_m = l.phase_vocoder(D_harm_melody, rate=new_rate, hop_length=512)
D_fast_harm_b = l.phase_vocoder(D_harm_bass, rate=new_rate, hop_length=512)

# 2. Process percussive part using simple Time-Domain Resampling 
# (Transients hate the frequency domain)
y_fast_drums = l.effects.time_stretch(y_drums, rate=new_rate) # Uses a more robust method
y_fast_vocals = l.effects.time_stretch(y_percussive_vocals, rate=new_rate) # Uses a more robust method
y_fast_melody = l.effects.time_stretch(y_percussive_melody, rate=new_rate) # Uses a more robust method
y_fast_bass = l.effects.time_stretch(y_percussive_bass, rate=new_rate) # Uses a more robust method

# 3. Combine them back together
y_fast_harm_v = l.istft(D_fast_harm_v)
y_fast_harm_m = l.istft(D_fast_harm_m)
y_fast_harm_b = l.istft(D_fast_harm_b)
min_len = min(len(y_fast_drums), len(y_fast_vocals), len(y_fast_melody), len(y_fast_bass), len(y_fast_harm_v), len(y_fast_harm_m), len(y_fast_harm_b))
y_final = y_fast_drums[:min_len] + y_fast_vocals[:min_len] + y_fast_melody[:min_len] + y_fast_bass[:min_len] + y_fast_harm_v[:min_len] + y_fast_harm_m[:min_len] + y_fast_harm_b[:min_len]
'''End Generated by Gemini'''

try:
    print("Playing... Press Ctrl+C to stop.")
    sd.play(y_final, sr)
    
    # Check every 0.1 seconds if the audio is still playing
    while sd.get_stream().active:
        time.sleep(0.1)

except KeyboardInterrupt:
    print("\nStopped by user.")
    sd.stop()  # Immediately kill the audio output